services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  redis:
    image: "redis:latest"
    command: bash -c "redis-server"
    ports:
      - "6379:6379"
  sidekiq:
    depends_on:
      - "redis"
    build: .
    command: bash -c "bundle exec sidekiq"
    volumes:
      - ".:/myapp"
    environment:
      - REDIS_URL_SIDEKIQ=redis://redis:6379/1
    platform: linux/x86_64
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    platform: linux/x86_64
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
